#!/usr/bin/env bash

## Update local environment
# Abort if anything fails
set -e

echo "START LOCAL SYNCHRONOZATION ..."
composer install
echo "Cleaning cache ..."
fin drush cr
echo "Importing configurations ..."
fin drush cim --partial -y
echo "Updating database ..."
fin drush updatedb -y
echo "Updating translation ..."
fin drush pm-enable locale -y
fin drush locale-check -y
fin drush locale-update -y
echo "Cleaning cache ..."
fin drush cr
echo "END LOCAL SYNCHRONOZATION"
